version: 2
experimental:
  pipelines: true
jobs:
  contentful: 
    docker: # run the steps with Docker as with build job
      - image: dickeyxxx/heroku-cli # tryin this out eek
    steps:
      - checkout
      - run:
        name: force deploy to heroku from circleci
        command: heroku builds:create --source-url https://shannonzylstra:$GITHUB_TOKEN@api.github.com/repos/shannonzylstra/contentful-gatsby-blog/tarball/master/ --app $HEROKU_APP_NAME
  build:
    docker: # run the steps with Docker
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
workflows:
  version: 2
  build:
    jobs:
    - build: {}
  contentful:
    jobs:
    - contentful: {}
